### ISSUE TITLE
Mechanism to load demo data from file

### ISSUE THREAD

**Issue by jldec** [tanzu-mkondo/inventory-management#6]
For demo purposes we need an easy way to bulk-load sample inventory data.
This would be the first step to set up the demo after installing the inventory db and app
The instructions for this should become part of the readme E.g. 

- start with a csv or json file containing just the demo data (please add a sample to this repo)
- run a single command to copy the data into the db

**Comment by fbiville** [comment]
The easiest is to deploy the API (as documented in the README), port-forward the service and execute a bunch of curl commands.

**Comment by fbiville** [comment]
Once both frontend and backend are deployed (see README), you can send as many HTTP requests as you want.
 
Here is an example of a working curl execution (the `imageUrl` attribute is optional):
```
address=$(kubectl get service/inventory-gui -ojson | jq -r '.status.loadBalancer.ingress[0].ip')
curl -v http://$address/api/article --header 'Content-Type:application/json' --data '{"sku": "some SKU", "name": "some name", "description": "some description", "quantity": 2, "priceInUsd": 42, "imageUrl": "https://media.giphy.com/media/yR4xZagT71AAM/giphy.gif"}'
```

The GUI pod actually runs a proxy that forwards `/api/*` requests to the API pod (which is why we extract the address from the `service/inventory-gui`).
